---
bibliography: bio.bib
csl: harvard-cite-them-right.csl
title: Data Biography
format: 
  pdf:
    include-in-header:
      text: |
        \addtokomafont{disposition}{\rmfamily}
    #documentclass: report
    # If using Quarto in Docker, available fonts are: `fc-list : family | sort | uniq`
    # If using Quarto on local machine then you can usually pick them from the list of installed fonts
    mainfont: "Spectral" # https://fonts.google.com/specimen/Spectral
    sansfont: "Roboto"   # https://fonts.google.com/specimen/Roboto?category=Sans+Serif
    monofont: "Inconsolata" # https://fonts.google.com/specimen/Inconsolata
    papersize: a4
    geometry:
      - top=25mm
      - left=40mm
      - right=30mm
      - bottom=25mm
      - heightrounded
    toc: false
    number-sections: true
    colorlinks: true
    highlight-style: github
---

## Declaration of Authorship {.unnumbered .unlisted}

I, Jiahao Wu, confirm that the work presented in this assessment is my own. Where information has been derived from other sources, I confirm that this has been indicated in the work.

['Sign' your name here]

Date: 16/11/2022

Student Number: 22081107

## Who collected the data?

An inline citation: As discussed on @insideairbnb, there are many...

A parenthetical citation: There are many ways to research Airbnb [see, for example, @insideairbnb].

The data is collected from publicly available information from the Airbnb site.

## Why did they collect it?
1. To facilitate public discussion.
2. Data and information empower communities to understand, decide the role of renting residential homes to tourists.
3. Quantifying the impact of short-term rentals on housing and residential communities.
4. Creating a platform to support advocacy for policies to avoid the impacts of short-term rentals.
## How was it collected?
The data utilizes public information compiled from the Airbnb website. No private information is being used. Names, photographs, listings and review details in many cities from all over the world are all publicly displayed on the Airbnb site. Data is verified, cleansed, analyzed and aggregated. Inside Airbnb uses an occupancy models "San Francisco Model" to verify whether properties are rent permanently or occasionally. The whole process involve technologies like Python, PostgreSQL, etc. 

## What useful information does it contain?


## To what extent is the data 'complete'?

## What kinds of analysis would this support?

## Which of the analyses outlined above are ethical?

## References
